const handleQuestions = {
    "cute": [
      "A partir de que momento você percebeu que estava interessado em mim?",
      "Quando me viu pela primeira vez, o que mais chamou sua atenção?",
      "Onde nos beijamos pela primeira vez?",
      "Quando nos beijamos pela primeira vez, você sentiu algo diferente?",
      "Depois da primeira vez que ficamos, quem teve a iniciativa de entrar em contato no dia seguinte?",
      "A partir de que momento você percebeu que nossa relação se tornaria séria?",
      "Em relação à minha personalidade, o que mais te agrada?",
      "O que você sente quando nos abraçamos?",
      "Qual é a primeira coisa que vem à sua mente quando você se lembra de mim no dia a dia?",
      "Como você se sente quando ficamos separados por mais tempo (do que estamos acostumados)?",
      "Você tem vontade de me apresentar para os seus pais?",
      "Você tem vontade de me apresentar para os seus melhores amigos e/ou amigos de infância?",
      "O que você fala de mim para seus amigos?",
      "O que você responde quando as pessoas perguntam por que você se interessou por mim?",
      "Você consegue lembrar o que eu vestia no dia em que nos conhecemos?",
      "O que te faz sentir ciúmes de mim?",
      "Que música você acha que pode definir nossa relação?",
      "Quais músicas você escuta e se lembra de mim?",
      "Por que você me ama?",
      "Se você fosse me descrever em uma palavra, qual palavra seria?",
      "Você prefere me beijar rapidamente ou me abraçar mais lentamente quando estamos em público?",
      "Você escreveria um poema sobre mim?",
      "Você ainda sente o coração acelerar quando me encontra?",
      "Em algum momento você questionou se deveria mesmo me namorar?",
      "Você fica ansioso quando estamos prestes a nos encontrar?",
      "Você sorri quando recebe uma mensagem minha no celular?",
      "Você fica curioso e animado quando vê que eu estou ligando para você?",
      "Em tempos de WhatsApp como o principal meio de comunicação, você gostaria de falar mais comigo ao telefone?",
      "Você costuma sonhar comigo?",
      "Você lembra qual foi o primeiro filme que vimos juntos?",
      "Você lembra qual foi o primeiro restaurante em que jantamos juntos?",
      "Qual foi nossa primeira viagem?",
      "Qual foi o melhor filme que vimos juntos no cinema?",
      "Qual foi o pior filme que assistimos juntos?",
      "O que você ainda não sabe sobre mim?",
      "O que você sabe sobre minha infância?",
      "O que mudou na sua forma de pensar depois que começamos a namorar?",
      "Se eu fosse uma flor, qual flor eu seria?",
      "Qual foi o primeiro presente que eu te dei?",
      "Qual foi o primeiro presente que você me deu?",
      "Quando você está sozinho, pensa em mim?",
      "Às vezes você tem vontade de me escrever ou ligar, mas deixa de fazer isso com medo de “me incomodar” e/ou “ser pegajoso(a)”?",
      "Você me contaria um segredo agora se eu contasse um meu?",
      "Se você vê alguém me olhando e/ou flertando comigo, o que você sente?",
      "Você fica bravo(a) se alguém diz que sou bonita?",
      "Se você pudesse definir nosso relacionamento em até três palavras, quais palavras usaria?",
      "Você faria um jantar romântico para mim?",
      "Você se sente seguro(a) comigo?",
      "Se tivéssemos nos conhecido antes do que nos conhecemos, você acha que teríamos nos apaixonado da mesma forma?",
      "Quando você assiste a uma comédia romântica ou a um romance, você pensa em mim?"
    ],
    "fun": [
      "Qual mania minha você acha mais engraçada?",	
      "Qual defeito meu mais te irrita?",	
      "Em que momentos eu te faço rir?",	
      "Você iria comigo ao cinema para ver um tipo de filme que você não gosta?",	
      "Você dançaria comigo em um bar ou restaurante cheio de gente?",	
      "Você pediria minha mão em casamento em um bar ou restaurante cheio de gente?",	
      "Se fosse pedir minha mão em casamento hoje, como seria? Você se ajoelharia?",	
      "Se você me pedisse em casamento e eu dissesse que “por enquanto não”, você continuaria comigo?",	
     "Se eu fosse um estilo musical, qual seria?",	
      "O que você acha dos meus pés?",	
      "Se eu fosse levar café na cama para você amanhã, o que você gostaria de ver na bandeja?",	
      "Se fosse preparar um café e levar na cama para mim amanhã, o que você colocaria?",	
      "Se fôssemos viajar hoje, para onde iríamos?",	
      "Você me levaria hoje para uma viagem com sua família?",	
      "Eu faço algo que te deixa constrangido(a)/envergonhado(a)?",	
      "Qual é a maior loucura que você já fez?",	
      "Por qual famosa(o) você me trocaria?",	
      "Você acha que somos mais um casal “descolado” ou “careta”?",	
      "Qual foi sua experiência sexual mais cômica?",	
      "Se eu fosse uma estação do ano, qual seria?",	
      "Se eu fosse uma comida, qual seria?",	
      "O que você nunca pretende comer na vida?",	
      "O que você faria se eu preparasse um jantar surpresa com alimentos que você não gosta?",	
      "Como você acha que as pessoas te enxergam?",	
      "Você já se sentiu atraído por alguém já estando comigo?",	
      "Se você pudesse ter qualquer animal de estimação, qual escolheria?",	
      "Se tivéssemos um cachorro ou um gato hoje, como ele chamaria?",	
      "Se você pudesse comer somente um tipo de alimento pelo resto da sua vida, qual escolheria?",	
      "Se eu pudesse comer somente um tipo de alimento pelo resto da minha vida, você sabe qual eu escolheria?",	
      "Com que tipo de roupa você acha que nunca me verá?",	
      "Que tipo de aventura você acha que nunca me verá fazendo?",	
      "Quais são as três coisas que você não pode viver sem?",	
      "Se você fosse invisível por um dia, o que faria?",	
      "Se você pudesse fazer três pedidos ao “gênio da lâmpada”, quais seriam?",	
      "Se fôssemos ter um bebê em breve, como ele (ou ela) chamaria?",	
      "Qual era seu desenho de infância preferido?",	
      "De todas as pessoas que você conhece, qual considera a mais legal?",	
      "Se você pegar um peixe, o que fará com ele?",	
      "Em que brinquedo você não vai em um parque de diversão?",	
      "Qual a situação mais embaraçosa que você já viveu?",	
      "Qual você considera a maior invenção dos últimos tempos?",	
      "O que você acha que ainda precisam inventar?",	
      "Se você fosse fazer uma tatuagem hoje, qual seria?",	
      "Que tipo de roupa você nunca usaria (e odiaria se eu te desse de presente)?",	
      "O que você faria se eu te desse um presente e você não gostasse? (Disfarçaria ou diria a verdade?)",	
      "Qual comida faz você se lembrar de mim?",	
      "O que você dizia que queria ser quando crescesse?",	
      "Se você tivesse que viver em uma ilha deserta com apenas um amigo, qual você escolheria?",	
      "Quando você pensava em alguém para namorar, você pensava em uma pessoa com personalidade parecida ou totalmente diferente da minha?",	
      "Você faria alguma loucura de amor por mim?"
    ], 
    "hot": [
      "Já participou de um encontro às cegas? Teria coragem?",
      "Você lembra como foi seu primeiro beijo?",
      "Você consegue colocar limites quando não gosta de algo na relação?",
      "Qual é a sua parte favorita do corpo?",
      "O que mais te atrai em uma pessoa?",
      "Como foi sua primeira vez?",
      "Você é sexualmente ative?",
      "Está satisfeite com sua vida sexual?",
      "Gosta de massagens?",
      "Você já teve sonhos eróticos?",
      "Das coisas que te pediram na cama, qual foi a mais estranha?",
      "Qual foi a melhor experiência que você já viveu no sexo?",
      "Há alguma coisa que você nunca faria durante o sexo?",
      "Você conseguiria adivinhar o que estou vestindo por baixo?",
      "O que é preliminar para você?",
      "Você já gozou nas preliminares?",
      "Você possui fetiche(s)?",
      "Qual é seu maior fetiche na cama?",
      "Qual palavra te descreve no sexo?",
      "Você prefere locais íntimos ou móteis?",
      "Sexo é essencial para você?",
      "Com que frequência você transa?",
     "Na hora do sexo, você gosta de dominar ou ser dominade?",
      "Qual é posição sexual que você mais gosta?",
      "O que você mais gosta que te façam durante a transa?",
      "Quais as zonas erógenas mais sensíveis para você?",
      "Você gosta de romance no sexo?",
      "Qual a coisa mais romântica na hora da transa para você?",
      "Você gosta de beijos pelo corpo?",
      "Onde você gostaria que eu te tocasse?",
      "Possui alguma fantasia sexual?",
      "Gosta que fale algo durante o sexo? Que frase te excita?",
      "Você acha danças sensuais excitantes?",
      "O que você acha de uns tapinhas durante o sexo?",
      "Gosta de ouvir música quando transa?",
      "Para você, vale tudo entre quatro paredes?",
      "Qual parte do meu corpo você gosta mais?",
      "Você guarda alguma fantasia sexual comigo?",
      "Tem vontade de fazer um ménage?",
      "Já participou de uma orgia? Se não, tem vontade?",
      "Qual é o lugar mais estranho no qual você já transou?",
      "Você gosta de fazer e receber sexo oral?",
     "Qual posição sexual você tem vontade de experimentar?",
     "No sexo, prefere ficar em cima ou embaixo?",
     "Em que locais você nos imagina transando?",
     "Com qual roupa íntima você me imaginou?",
     "Qual posição você quer fazer comigo?",
      "Você se masturba? Gosta de masturbação?",
      "Você já fez striptease?",
      "Já recebeu um striptease?",
      "Já fez sexo 69? Gostou?",
      "Já fez sexo em local público?",
      "Você já se masturbou pensando em mim?",
      "Você já pensou em fazer sexo anal?",
      "Já fez sexo anal?",
      "O que você faria se estivéssemos na sua cama agora?",
      "Por qual parte do meu corpo você começaria uma massagem?",
      "Se pudesse me tocar em apenas um lugar do corpo, onde seria?",
      "Você quer beijar qual parte do meu corpo agora?",
      "Se você pudesse fazer qualquer coisa comigo, o que seria?",
      "Você conseguiria tirar minha roupa íntima sem usar as mãos?",
      "Você gosta quando eu sou safade com você?",
     "Posso sentar na sua cara?",
      "Qual foi a melhor coisa que te fizeram no sexo?",
      "Qual sua opinião sobre usar sex toys na cama?",
      "Você já usou algemas? Tem vontade?",
      "Já usou vibrador durante o sexo? Como foi?",
      "Tem vontade de praticar BDSM?",
      "Você grita quando goza?",
      "Já errou o nome da pessoa na hora H?",
      "Gosta de transar olhando nos olhos?",
     "Qual lugar mais improvável onde você fez sexo?",
      "Você já fez sexo no banheiro?",
      "Faria sexo na cozinha?",
      "Já fez sexo ao ar livre, no quintal, por exemplo?",
      "Já transou no carro?",
      "Você já fez posições sexuais em pé?",
      "Já transou no chão?",
      "Você gosta de filmes pornográficos?",
      "O que você já disse de mais vulgar na hora do sexo?",
      "Qual foi a coisa mais romântica que você falou na hora H?",
      "Gosta de transar com a luz acesa ou apagada?",
      "Alguém já te pegou transando?",
      "Você gosta de assistir pessoas transando?",
      "Já fez sexo com alguém assistindo?",
      "Você já fez role play no sexo?",
      "Gosta de camisinha com sabor?",
      "Você fingiu que teve um orgasmo?",
      "Você se sente à vontade para se masturbar? Por quê?",
      "Gosta de sexo casual?",
      "Se tivesse algum problema sexual, ficaria à vontade para buscar ajuda?",
      "Você já escondeu uma fantasia da outra pessoa?",
      "Você faz exames de infecções sexualmente transmissível regularmente?",
      "Com quantos anos teve sua primeira relação?",
      "Conversas como essa te deixam excitade?",
      "Você já fez sexo oral ou transou em um carro?",
      "O que se passa na sua cabeça durante o sexo?",
      "Você já trocou nudes? Como se sentiu?",
      "Você já praticou sexting com alguém?",
      "Você já ficou excitade ao trocar mensagens pelo celular?",
      "Você me enviaria fotos sem roupa se eu pedisse?",
      "Você já se gravou transando?",
      "Você gostaria que eu me filmasse para você?"
     
    ]
}

export default handleQuestions;